### ISSUE TITLE
Following tutorial, ran into a couple of issues

### ISSUE THREAD

**Issue by ssteinerx** [owais/owais.github.com#2]
Following along with great (tutorial)[   http://owaislone.org/blog/webpack-plus-reactjs-and-django/]

And ran into a couple of dead ends.

(This)[https://edwardsamuel.wordpress.com/2015/11/01/react-syntax-error-unexpected-token/] got me over the first hump, had to follow this instruction

> So, in order to use BabelJS 6 with React and ES6, we need to use babel-preset-react and babel-preset-es2015 by running:

by doing:

```
npm install --save-dev babel-preset-react babel-preset-es2015
```

I had to add a .babelrc, and fill it with:

```
{
      "presets": ["es2015", "react"] 
}
```

Also modified my webpack.config.js, though I'm not sure it's necessary:

```
module: {
    loaders: [
      { test: /\.jsx?$/, exclude: /node_modules/, loader: 'babel-loader'}, // to transform JSX into JS
      { entry:/\.jsx?$/, loader: 'babel-loader'}
    ],
  },
```

The files are now being properly transpiled and stored in the correct location.

**Comment by owais** [comment]
Any issues related to the blog should be opened at https://github.com/owais/owais.github.com-source/
