### ISSUE TITLE
After additions in #1, specified <div> not being modified at runtime

### ISSUE THREAD

**Issue by ssteinerx** [owais/owais.github.com#3]
Django: 1.10
node: v6.3.1
npm: 3.10.3
[requirements.txt](https://github.com/owais/owais.github.com/files/429129/requirements.txt)

After making the additions in #1, the correct script tag is being inserted, and the appropriate `<div id="react-app"></div>` is there in the page source, but the rendering:

```
React.render(<Hello />, document.getElementById('react-app'))
```

Never takes place.

Also, if I insert (just above the React.render call above):

```
alert("I'm in index.jsx");
```

The alert never shows up.

Both the declaration of the `<div id="react-app"></div>` and the `{% render_bundle 'main' %}` are in base.html to avoid any confusion of their being included.

I'm *very fuzzy* about the order of execution here so perhaps you can shed some light on this?

Great stuff, hopefully my comments can help us make it better, thanks!

**Comment by owais** [comment]
> The alert never shows up.
Is the javascript bundle downloaded by the browser at all? Check network tab of your dev console to confirm.

**Comment by ssteinerx** [comment]
Yes, it's properly loaded, it just doesn't fire.

**Comment by ssteinerx** [comment]
Or, if it does, it happens before the DOM is completely loaded and misfires.

**Comment by ssteinerx** [comment]
Nothing in the console, either.

**Comment by owais** [comment]
Component not rendering could be an issue with the placement of the script tag but if log and alert doesn't work then the issue is something else entirely. This is not really a webpack-loader issue as the bundle does load like you said. Most likely an issue with your webpack config. You should ask for help in webpack's IRC/github/slack/.

Do paste your webpack config here and I'll see if I can spot any obvious issues.

**Comment by ssteinerx** [comment]
```
var path = require("path")
var webpack = require('webpack')
var BundleTracker = require('webpack-bundle-tracker')

module.exports = {
  context: __dirname,
  // entry point of our app. assets/js/index.js should require other
  // js modules and dependencies it needs
  entry: './assets/js/index',

  output: {
      path: path.resolve('./assets/bundles/'),
      filename: "[name]-[hash].js",
  },

  plugins: [
    new BundleTracker({filename: './webpack-stats.json'}),
  ],

  module: {
    loaders: [
      { test: /\.jsx?$/, exclude: /node_modules/, loader: 'babel-loader'}, // to transform JSX into JS
      { entry:/\.jsx?$/, loader: 'babel-loader'}
    ],
  },

  resolve: {
    modulesDirectories: ['node_modules', 'bower_components'],
    extensions: ['', '.js', '.jsx']
  },
}
```
